// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:688fd63b-1cae-4c85-9855-5e8ac4930883",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Vt615hRRL",
    "aws_user_pools_web_client_id": "6oiqbluog3cet1lhku8719c3rs",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pf63hubtonfg7poy2albx2qjk4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-44kn6qqvxvdfrgc6jzsgzdgh7e"
};


export default awsmobile;
