// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:688fd63b-1cae-4c85-9855-5e8ac4930883",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Vt615hRRL",
    "aws_user_pools_web_client_id": "6oiqbluog3cet1lhku8719c3rs",
    "oauth": {}
};


export default awsmobile;
